version: '3.8'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: ${APP_IMAGE:-jimmyruan/docu-pet-api-image:latest}
    platform: linux/amd64
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - dp-network
    depends_on:
      - mysql
      - redis
    command: tail -f /dev/null
    container_name: DocuPet_backend

  node:
    image: node:22.11.0
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    command: tail -f /dev/null
    networks:
      - dp-network
    container_name: DocuPet_frontend

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dp-network
    ports:
      - 80:80
    depends_on:
      - app
    container_name: DocuPet_nginx

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dp-network
    container_name: DocuPet_mysql

  redis:
    image: redis:alpine
    networks:
      - dp-network
    container_name: DocuPet_redis

networks:
  dp-network:
    driver: bridge

volumes:
  mysql-data:
