version: '3.8'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: ${APP_IMAGE:-jimmyruan/docu-pet-api-image:latest}
    platform: linux/amd64
    working_dir: /var/www/api-app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - dp-network
    depends_on:
      - mysql
    command: tail -f /dev/null
    container_name: DocuPet_api

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dp-network
    container_name: DocuPet_mysql

networks:
  dp-network:
    driver: bridge

volumes:
  mysql-data:
